#!/bin/bash

SCRIPT=${BASH_SOURCE[0]##*/}
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

CHECK_FILE=$(command -v file)
EXIFTOOL=$(command -v exiftool)
QPDF=$(command -v qpdf)

if [[ -z "$1" ]]; then
  >&2 echo "Usage: '$SCRIPT <pdf>'"
  exit 1
fi

if [[ -z $CHECK_FILE || -z $EXIFTOOL || -z $QPDF ]]; then
  >&2 echo "Missing one of the following '$SCRIPT' dependencies: ['file', 'exiftool', 'qpdf']."
  exit 1
fi

pdf="$1"
type="$($CHECK_FILE -b $pdf)"
if [[ ${type%% *} != "PDF" ]]; then
  >&2 echo "File is not a PDF document"
  exit 1
fi

echo "Stripping metadata with exiftool..."
$EXIFTOOL -overwrite_original_in_place -all= "$pdf"

echo "Linearizing with qpdf..."
$QPDF --linearize --replace-input "$pdf"
